### ISSUE TITLE
运行报错 No visible @interface for 'EaseChatViewController' declares the selector 'formatMessages:'

### ISSUE THREAD

**Issue by xieyi94** [easemob/chat-ios#17]
No visible @interface for 'EaseChatViewController' declares the selector 'formatMessages:'

**Comment by dujiepeng** [comment]
您好，确实有一个方法没有暴露，您可以先在EaseIMKit.framework/Headers/EaseChatViewController.h
中添加一个方法声明：
- (NSArray *)formatMessages:(NSArray<EMMessage *> *)aMessages;
